2025-01-11 18:53:49,670 INFO    MainThread:2807263 [wandb_setup.py:_flush():68] Current SDK version is 0.19.2
2025-01-11 18:53:49,670 INFO    MainThread:2807263 [wandb_setup.py:_flush():68] Configure stats pid to 2807263
2025-01-11 18:53:49,671 INFO    MainThread:2807263 [wandb_setup.py:_flush():68] Loading settings from /home/lijinrun/.config/wandb/settings
2025-01-11 18:53:49,671 INFO    MainThread:2807263 [wandb_setup.py:_flush():68] Loading settings from /home/lijinrun/lgs/Roberta-Llama-Mistral/wandb/settings
2025-01-11 18:53:49,671 INFO    MainThread:2807263 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-11 18:53:49,671 INFO    MainThread:2807263 [wandb_init.py:_log_setup():523] Logging user logs to /home/lijinrun/lgs/Roberta-Llama-Mistral/wandb/run-20250111_185349-13dyplpe/logs/debug.log
2025-01-11 18:53:49,671 INFO    MainThread:2807263 [wandb_init.py:_log_setup():524] Logging internal logs to /home/lijinrun/lgs/Roberta-Llama-Mistral/wandb/run-20250111_185349-13dyplpe/logs/debug-internal.log
2025-01-11 18:53:49,671 INFO    MainThread:2807263 [wandb_init.py:init():641] calling init triggers
2025-01-11 18:53:49,671 INFO    MainThread:2807263 [wandb_init.py:init():647] wandb.init called with sweep_config: {}
config: {}
2025-01-11 18:53:49,671 INFO    MainThread:2807263 [wandb_init.py:init():674] starting backend
2025-01-11 18:53:49,880 INFO    MainThread:2807263 [wandb_init.py:init():678] sending inform_init request
2025-01-11 18:53:49,885 INFO    MainThread:2807263 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-11 18:53:49,885 INFO    MainThread:2807263 [wandb_init.py:init():693] backend started and connected
2025-01-11 18:53:49,887 INFO    MainThread:2807263 [wandb_init.py:init():786] updated telemetry
2025-01-11 18:53:49,893 INFO    MainThread:2807263 [wandb_init.py:init():818] communicating run to backend with 90.0 second timeout
2025-01-11 18:55:19,920 ERROR   MainThread:2807263 [wandb_init.py:init():845] encountered error: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-01-11 18:55:19,920 ERROR   MainThread:2807263 [wandb_init.py:init():1299] error in wandb.init()
Traceback (most recent call last):
  File "/home/lijinrun/anaconda3/envs/class2/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1289, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/lijinrun/anaconda3/envs/class2/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 851, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-01-11 18:55:19,932 WARNING MsgRouterThr:2807263 [router.py:message_loop():75] message_loop has been closed
